# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: redcarpet


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: "Mobile Development with PhoneGap, AngularJS and REST API"

description: "haring Experience about Mobile Development with PhoneGap, AngularJS and REST API"
author:
  name: meumobi
  email: contact@meumobi.com
  github: meumobi
  twitter: meumobi
  bio: Sharing mobile Experiences
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH: /infoMobi

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: meumobi-dev
